/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YhteysRouteImport } from './routes/yhteys'
import { Route as MeistaRouteImport } from './routes/meista'
import { Route as KotisivutYrityksilleRouteImport } from './routes/kotisivut-yrityksille'
import { Route as DiginakyvyysRouteImport } from './routes/diginakyvyys'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as IndexRouteImport } from './routes/index'

const YhteysRoute = YhteysRouteImport.update({
  id: '/yhteys',
  path: '/yhteys',
  getParentRoute: () => rootRouteImport,
} as any)
const MeistaRoute = MeistaRouteImport.update({
  id: '/meista',
  path: '/meista',
  getParentRoute: () => rootRouteImport,
} as any)
const KotisivutYrityksilleRoute = KotisivutYrityksilleRouteImport.update({
  id: '/kotisivut-yrityksille',
  path: '/kotisivut-yrityksille',
  getParentRoute: () => rootRouteImport,
} as any)
const DiginakyvyysRoute = DiginakyvyysRouteImport.update({
  id: '/diginakyvyys',
  path: '/diginakyvyys',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/diginakyvyys': typeof DiginakyvyysRoute
  '/kotisivut-yrityksille': typeof KotisivutYrityksilleRoute
  '/meista': typeof MeistaRoute
  '/yhteys': typeof YhteysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/diginakyvyys': typeof DiginakyvyysRoute
  '/kotisivut-yrityksille': typeof KotisivutYrityksilleRoute
  '/meista': typeof MeistaRoute
  '/yhteys': typeof YhteysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/diginakyvyys': typeof DiginakyvyysRoute
  '/kotisivut-yrityksille': typeof KotisivutYrityksilleRoute
  '/meista': typeof MeistaRoute
  '/yhteys': typeof YhteysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatbot'
    | '/diginakyvyys'
    | '/kotisivut-yrityksille'
    | '/meista'
    | '/yhteys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/diginakyvyys'
    | '/kotisivut-yrityksille'
    | '/meista'
    | '/yhteys'
  id:
    | '__root__'
    | '/'
    | '/chatbot'
    | '/diginakyvyys'
    | '/kotisivut-yrityksille'
    | '/meista'
    | '/yhteys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatbotRoute: typeof ChatbotRoute
  DiginakyvyysRoute: typeof DiginakyvyysRoute
  KotisivutYrityksilleRoute: typeof KotisivutYrityksilleRoute
  MeistaRoute: typeof MeistaRoute
  YhteysRoute: typeof YhteysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yhteys': {
      id: '/yhteys'
      path: '/yhteys'
      fullPath: '/yhteys'
      preLoaderRoute: typeof YhteysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meista': {
      id: '/meista'
      path: '/meista'
      fullPath: '/meista'
      preLoaderRoute: typeof MeistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotisivut-yrityksille': {
      id: '/kotisivut-yrityksille'
      path: '/kotisivut-yrityksille'
      fullPath: '/kotisivut-yrityksille'
      preLoaderRoute: typeof KotisivutYrityksilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diginakyvyys': {
      id: '/diginakyvyys'
      path: '/diginakyvyys'
      fullPath: '/diginakyvyys'
      preLoaderRoute: typeof DiginakyvyysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatbotRoute: ChatbotRoute,
  DiginakyvyysRoute: DiginakyvyysRoute,
  KotisivutYrityksilleRoute: KotisivutYrityksilleRoute,
  MeistaRoute: MeistaRoute,
  YhteysRoute: YhteysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
