/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YllapitoRouteImport } from './routes/yllapito'
import { Route as YhteysRouteImport } from './routes/yhteys'
import { Route as VerkkosivutRouteImport } from './routes/verkkosivut'
import { Route as PoytavaraupalveluRouteImport } from './routes/poytavaraupalvelu'
import { Route as NakyvyysJaSuunnitteluRouteImport } from './routes/nakyvyys-ja-suunnittelu'
import { Route as MeistaRouteImport } from './routes/meista'
import { Route as HinnastoRouteImport } from './routes/hinnasto'
import { Route as AiAsiakaspalveluRouteImport } from './routes/ai-asiakaspalvelu'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVisitorsRouteImport } from './routes/dashboard/visitors'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReservationsRouteImport } from './routes/dashboard/reservations'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardFloorPlanRouteImport } from './routes/dashboard/floor-plan'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard/conversations'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiRestaurantSettingsRouteImport } from './routes/api/restaurant/settings'
import { Route as ApiDashboardVisitorsRouteImport } from './routes/api/dashboard/visitors'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiDashboardSettingsRouteImport } from './routes/api/dashboard/settings'
import { Route as ApiDashboardReservationsRouteImport } from './routes/api/dashboard/reservations'
import { Route as ApiDashboardLeadsRouteImport } from './routes/api/dashboard/leads'
import { Route as ApiDashboardFloorPlanRouteImport } from './routes/api/dashboard/floor-plan'
import { Route as ApiDashboardConversationsRouteImport } from './routes/api/dashboard/conversations'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiDashboardReservationsIdRouteImport } from './routes/api/dashboard/reservations/$id'
import { Route as ApiDashboardLeadsIdRouteImport } from './routes/api/dashboard/leads/$id'
import { Route as ApiDashboardConversationsSessionIdRouteImport } from './routes/api/dashboard/conversations/$sessionId'

const YllapitoRoute = YllapitoRouteImport.update({
  id: '/yllapito',
  path: '/yllapito',
  getParentRoute: () => rootRouteImport,
} as any)
const YhteysRoute = YhteysRouteImport.update({
  id: '/yhteys',
  path: '/yhteys',
  getParentRoute: () => rootRouteImport,
} as any)
const VerkkosivutRoute = VerkkosivutRouteImport.update({
  id: '/verkkosivut',
  path: '/verkkosivut',
  getParentRoute: () => rootRouteImport,
} as any)
const PoytavaraupalveluRoute = PoytavaraupalveluRouteImport.update({
  id: '/poytavaraupalvelu',
  path: '/poytavaraupalvelu',
  getParentRoute: () => rootRouteImport,
} as any)
const NakyvyysJaSuunnitteluRoute = NakyvyysJaSuunnitteluRouteImport.update({
  id: '/nakyvyys-ja-suunnittelu',
  path: '/nakyvyys-ja-suunnittelu',
  getParentRoute: () => rootRouteImport,
} as any)
const MeistaRoute = MeistaRouteImport.update({
  id: '/meista',
  path: '/meista',
  getParentRoute: () => rootRouteImport,
} as any)
const HinnastoRoute = HinnastoRouteImport.update({
  id: '/hinnasto',
  path: '/hinnasto',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAsiakaspalveluRoute = AiAsiakaspalveluRouteImport.update({
  id: '/ai-asiakaspalvelu',
  path: '/ai-asiakaspalvelu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVisitorsRoute = DashboardVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReservationsRoute = DashboardReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFloorPlanRoute = DashboardFloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantSettingsRoute = ApiRestaurantSettingsRouteImport.update({
  id: '/api/restaurant/settings',
  path: '/api/restaurant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardVisitorsRoute = ApiDashboardVisitorsRouteImport.update({
  id: '/api/dashboard/visitors',
  path: '/api/dashboard/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardSettingsRoute = ApiDashboardSettingsRouteImport.update({
  id: '/api/dashboard/settings',
  path: '/api/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardReservationsRoute =
  ApiDashboardReservationsRouteImport.update({
    id: '/api/dashboard/reservations',
    path: '/api/dashboard/reservations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardLeadsRoute = ApiDashboardLeadsRouteImport.update({
  id: '/api/dashboard/leads',
  path: '/api/dashboard/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardFloorPlanRoute = ApiDashboardFloorPlanRouteImport.update({
  id: '/api/dashboard/floor-plan',
  path: '/api/dashboard/floor-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardConversationsRoute =
  ApiDashboardConversationsRouteImport.update({
    id: '/api/dashboard/conversations',
    path: '/api/dashboard/conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardReservationsIdRoute =
  ApiDashboardReservationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiDashboardReservationsRoute,
  } as any)
const ApiDashboardLeadsIdRoute = ApiDashboardLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDashboardLeadsRoute,
} as any)
const ApiDashboardConversationsSessionIdRoute =
  ApiDashboardConversationsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ApiDashboardConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/ai-asiakaspalvelu': typeof AiAsiakaspalveluRoute
  '/hinnasto': typeof HinnastoRoute
  '/meista': typeof MeistaRoute
  '/nakyvyys-ja-suunnittelu': typeof NakyvyysJaSuunnitteluRoute
  '/poytavaraupalvelu': typeof PoytavaraupalveluRoute
  '/verkkosivut': typeof VerkkosivutRoute
  '/yhteys': typeof YhteysRoute
  '/yllapito': typeof YllapitoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/track': typeof ApiTrackRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/floor-plan': typeof DashboardFloorPlanRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/dashboard/conversations': typeof ApiDashboardConversationsRouteWithChildren
  '/api/dashboard/floor-plan': typeof ApiDashboardFloorPlanRoute
  '/api/dashboard/leads': typeof ApiDashboardLeadsRouteWithChildren
  '/api/dashboard/reservations': typeof ApiDashboardReservationsRouteWithChildren
  '/api/dashboard/settings': typeof ApiDashboardSettingsRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/dashboard/visitors': typeof ApiDashboardVisitorsRoute
  '/api/restaurant/settings': typeof ApiRestaurantSettingsRoute
  '/api/dashboard/conversations/$sessionId': typeof ApiDashboardConversationsSessionIdRoute
  '/api/dashboard/leads/$id': typeof ApiDashboardLeadsIdRoute
  '/api/dashboard/reservations/$id': typeof ApiDashboardReservationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-asiakaspalvelu': typeof AiAsiakaspalveluRoute
  '/hinnasto': typeof HinnastoRoute
  '/meista': typeof MeistaRoute
  '/nakyvyys-ja-suunnittelu': typeof NakyvyysJaSuunnitteluRoute
  '/poytavaraupalvelu': typeof PoytavaraupalveluRoute
  '/verkkosivut': typeof VerkkosivutRoute
  '/yhteys': typeof YhteysRoute
  '/yllapito': typeof YllapitoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/track': typeof ApiTrackRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/floor-plan': typeof DashboardFloorPlanRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/dashboard/conversations': typeof ApiDashboardConversationsRouteWithChildren
  '/api/dashboard/floor-plan': typeof ApiDashboardFloorPlanRoute
  '/api/dashboard/leads': typeof ApiDashboardLeadsRouteWithChildren
  '/api/dashboard/reservations': typeof ApiDashboardReservationsRouteWithChildren
  '/api/dashboard/settings': typeof ApiDashboardSettingsRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/dashboard/visitors': typeof ApiDashboardVisitorsRoute
  '/api/restaurant/settings': typeof ApiRestaurantSettingsRoute
  '/api/dashboard/conversations/$sessionId': typeof ApiDashboardConversationsSessionIdRoute
  '/api/dashboard/leads/$id': typeof ApiDashboardLeadsIdRoute
  '/api/dashboard/reservations/$id': typeof ApiDashboardReservationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/ai-asiakaspalvelu': typeof AiAsiakaspalveluRoute
  '/hinnasto': typeof HinnastoRoute
  '/meista': typeof MeistaRoute
  '/nakyvyys-ja-suunnittelu': typeof NakyvyysJaSuunnitteluRoute
  '/poytavaraupalvelu': typeof PoytavaraupalveluRoute
  '/verkkosivut': typeof VerkkosivutRoute
  '/yhteys': typeof YhteysRoute
  '/yllapito': typeof YllapitoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/track': typeof ApiTrackRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/floor-plan': typeof DashboardFloorPlanRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/dashboard/conversations': typeof ApiDashboardConversationsRouteWithChildren
  '/api/dashboard/floor-plan': typeof ApiDashboardFloorPlanRoute
  '/api/dashboard/leads': typeof ApiDashboardLeadsRouteWithChildren
  '/api/dashboard/reservations': typeof ApiDashboardReservationsRouteWithChildren
  '/api/dashboard/settings': typeof ApiDashboardSettingsRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/dashboard/visitors': typeof ApiDashboardVisitorsRoute
  '/api/restaurant/settings': typeof ApiRestaurantSettingsRoute
  '/api/dashboard/conversations/$sessionId': typeof ApiDashboardConversationsSessionIdRoute
  '/api/dashboard/leads/$id': typeof ApiDashboardLeadsIdRoute
  '/api/dashboard/reservations/$id': typeof ApiDashboardReservationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/ai-asiakaspalvelu'
    | '/hinnasto'
    | '/meista'
    | '/nakyvyys-ja-suunnittelu'
    | '/poytavaraupalvelu'
    | '/verkkosivut'
    | '/yhteys'
    | '/yllapito'
    | '/api/chat'
    | '/api/track'
    | '/dashboard/conversations'
    | '/dashboard/floor-plan'
    | '/dashboard/leads'
    | '/dashboard/login'
    | '/dashboard/reservations'
    | '/dashboard/settings'
    | '/dashboard/visitors'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/dashboard/conversations'
    | '/api/dashboard/floor-plan'
    | '/api/dashboard/leads'
    | '/api/dashboard/reservations'
    | '/api/dashboard/settings'
    | '/api/dashboard/stats'
    | '/api/dashboard/visitors'
    | '/api/restaurant/settings'
    | '/api/dashboard/conversations/$sessionId'
    | '/api/dashboard/leads/$id'
    | '/api/dashboard/reservations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-asiakaspalvelu'
    | '/hinnasto'
    | '/meista'
    | '/nakyvyys-ja-suunnittelu'
    | '/poytavaraupalvelu'
    | '/verkkosivut'
    | '/yhteys'
    | '/yllapito'
    | '/api/chat'
    | '/api/track'
    | '/dashboard/conversations'
    | '/dashboard/floor-plan'
    | '/dashboard/leads'
    | '/dashboard/login'
    | '/dashboard/reservations'
    | '/dashboard/settings'
    | '/dashboard/visitors'
    | '/dashboard'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/dashboard/conversations'
    | '/api/dashboard/floor-plan'
    | '/api/dashboard/leads'
    | '/api/dashboard/reservations'
    | '/api/dashboard/settings'
    | '/api/dashboard/stats'
    | '/api/dashboard/visitors'
    | '/api/restaurant/settings'
    | '/api/dashboard/conversations/$sessionId'
    | '/api/dashboard/leads/$id'
    | '/api/dashboard/reservations/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/ai-asiakaspalvelu'
    | '/hinnasto'
    | '/meista'
    | '/nakyvyys-ja-suunnittelu'
    | '/poytavaraupalvelu'
    | '/verkkosivut'
    | '/yhteys'
    | '/yllapito'
    | '/api/chat'
    | '/api/track'
    | '/dashboard/conversations'
    | '/dashboard/floor-plan'
    | '/dashboard/leads'
    | '/dashboard/login'
    | '/dashboard/reservations'
    | '/dashboard/settings'
    | '/dashboard/visitors'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/dashboard/conversations'
    | '/api/dashboard/floor-plan'
    | '/api/dashboard/leads'
    | '/api/dashboard/reservations'
    | '/api/dashboard/settings'
    | '/api/dashboard/stats'
    | '/api/dashboard/visitors'
    | '/api/restaurant/settings'
    | '/api/dashboard/conversations/$sessionId'
    | '/api/dashboard/leads/$id'
    | '/api/dashboard/reservations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AiAsiakaspalveluRoute: typeof AiAsiakaspalveluRoute
  HinnastoRoute: typeof HinnastoRoute
  MeistaRoute: typeof MeistaRoute
  NakyvyysJaSuunnitteluRoute: typeof NakyvyysJaSuunnitteluRoute
  PoytavaraupalveluRoute: typeof PoytavaraupalveluRoute
  VerkkosivutRoute: typeof VerkkosivutRoute
  YhteysRoute: typeof YhteysRoute
  YllapitoRoute: typeof YllapitoRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTrackRoute: typeof ApiTrackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiDashboardConversationsRoute: typeof ApiDashboardConversationsRouteWithChildren
  ApiDashboardFloorPlanRoute: typeof ApiDashboardFloorPlanRoute
  ApiDashboardLeadsRoute: typeof ApiDashboardLeadsRouteWithChildren
  ApiDashboardReservationsRoute: typeof ApiDashboardReservationsRouteWithChildren
  ApiDashboardSettingsRoute: typeof ApiDashboardSettingsRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiDashboardVisitorsRoute: typeof ApiDashboardVisitorsRoute
  ApiRestaurantSettingsRoute: typeof ApiRestaurantSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yllapito': {
      id: '/yllapito'
      path: '/yllapito'
      fullPath: '/yllapito'
      preLoaderRoute: typeof YllapitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yhteys': {
      id: '/yhteys'
      path: '/yhteys'
      fullPath: '/yhteys'
      preLoaderRoute: typeof YhteysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verkkosivut': {
      id: '/verkkosivut'
      path: '/verkkosivut'
      fullPath: '/verkkosivut'
      preLoaderRoute: typeof VerkkosivutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poytavaraupalvelu': {
      id: '/poytavaraupalvelu'
      path: '/poytavaraupalvelu'
      fullPath: '/poytavaraupalvelu'
      preLoaderRoute: typeof PoytavaraupalveluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nakyvyys-ja-suunnittelu': {
      id: '/nakyvyys-ja-suunnittelu'
      path: '/nakyvyys-ja-suunnittelu'
      fullPath: '/nakyvyys-ja-suunnittelu'
      preLoaderRoute: typeof NakyvyysJaSuunnitteluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meista': {
      id: '/meista'
      path: '/meista'
      fullPath: '/meista'
      preLoaderRoute: typeof MeistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinnasto': {
      id: '/hinnasto'
      path: '/hinnasto'
      fullPath: '/hinnasto'
      preLoaderRoute: typeof HinnastoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-asiakaspalvelu': {
      id: '/ai-asiakaspalvelu'
      path: '/ai-asiakaspalvelu'
      fullPath: '/ai-asiakaspalvelu'
      preLoaderRoute: typeof AiAsiakaspalveluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/visitors': {
      id: '/dashboard/visitors'
      path: '/visitors'
      fullPath: '/dashboard/visitors'
      preLoaderRoute: typeof DashboardVisitorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reservations': {
      id: '/dashboard/reservations'
      path: '/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof DashboardReservationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/floor-plan': {
      id: '/dashboard/floor-plan'
      path: '/floor-plan'
      fullPath: '/dashboard/floor-plan'
      preLoaderRoute: typeof DashboardFloorPlanRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurant/settings': {
      id: '/api/restaurant/settings'
      path: '/api/restaurant/settings'
      fullPath: '/api/restaurant/settings'
      preLoaderRoute: typeof ApiRestaurantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/visitors': {
      id: '/api/dashboard/visitors'
      path: '/api/dashboard/visitors'
      fullPath: '/api/dashboard/visitors'
      preLoaderRoute: typeof ApiDashboardVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/settings': {
      id: '/api/dashboard/settings'
      path: '/api/dashboard/settings'
      fullPath: '/api/dashboard/settings'
      preLoaderRoute: typeof ApiDashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/reservations': {
      id: '/api/dashboard/reservations'
      path: '/api/dashboard/reservations'
      fullPath: '/api/dashboard/reservations'
      preLoaderRoute: typeof ApiDashboardReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/leads': {
      id: '/api/dashboard/leads'
      path: '/api/dashboard/leads'
      fullPath: '/api/dashboard/leads'
      preLoaderRoute: typeof ApiDashboardLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/floor-plan': {
      id: '/api/dashboard/floor-plan'
      path: '/api/dashboard/floor-plan'
      fullPath: '/api/dashboard/floor-plan'
      preLoaderRoute: typeof ApiDashboardFloorPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/conversations': {
      id: '/api/dashboard/conversations'
      path: '/api/dashboard/conversations'
      fullPath: '/api/dashboard/conversations'
      preLoaderRoute: typeof ApiDashboardConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/reservations/$id': {
      id: '/api/dashboard/reservations/$id'
      path: '/$id'
      fullPath: '/api/dashboard/reservations/$id'
      preLoaderRoute: typeof ApiDashboardReservationsIdRouteImport
      parentRoute: typeof ApiDashboardReservationsRoute
    }
    '/api/dashboard/leads/$id': {
      id: '/api/dashboard/leads/$id'
      path: '/$id'
      fullPath: '/api/dashboard/leads/$id'
      preLoaderRoute: typeof ApiDashboardLeadsIdRouteImport
      parentRoute: typeof ApiDashboardLeadsRoute
    }
    '/api/dashboard/conversations/$sessionId': {
      id: '/api/dashboard/conversations/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/dashboard/conversations/$sessionId'
      preLoaderRoute: typeof ApiDashboardConversationsSessionIdRouteImport
      parentRoute: typeof ApiDashboardConversationsRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardFloorPlanRoute: typeof DashboardFloorPlanRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardReservationsRoute: typeof DashboardReservationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVisitorsRoute: typeof DashboardVisitorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardFloorPlanRoute: DashboardFloorPlanRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardReservationsRoute: DashboardReservationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVisitorsRoute: DashboardVisitorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiDashboardConversationsRouteChildren {
  ApiDashboardConversationsSessionIdRoute: typeof ApiDashboardConversationsSessionIdRoute
}

const ApiDashboardConversationsRouteChildren: ApiDashboardConversationsRouteChildren =
  {
    ApiDashboardConversationsSessionIdRoute:
      ApiDashboardConversationsSessionIdRoute,
  }

const ApiDashboardConversationsRouteWithChildren =
  ApiDashboardConversationsRoute._addFileChildren(
    ApiDashboardConversationsRouteChildren,
  )

interface ApiDashboardLeadsRouteChildren {
  ApiDashboardLeadsIdRoute: typeof ApiDashboardLeadsIdRoute
}

const ApiDashboardLeadsRouteChildren: ApiDashboardLeadsRouteChildren = {
  ApiDashboardLeadsIdRoute: ApiDashboardLeadsIdRoute,
}

const ApiDashboardLeadsRouteWithChildren =
  ApiDashboardLeadsRoute._addFileChildren(ApiDashboardLeadsRouteChildren)

interface ApiDashboardReservationsRouteChildren {
  ApiDashboardReservationsIdRoute: typeof ApiDashboardReservationsIdRoute
}

const ApiDashboardReservationsRouteChildren: ApiDashboardReservationsRouteChildren =
  {
    ApiDashboardReservationsIdRoute: ApiDashboardReservationsIdRoute,
  }

const ApiDashboardReservationsRouteWithChildren =
  ApiDashboardReservationsRoute._addFileChildren(
    ApiDashboardReservationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AiAsiakaspalveluRoute: AiAsiakaspalveluRoute,
  HinnastoRoute: HinnastoRoute,
  MeistaRoute: MeistaRoute,
  NakyvyysJaSuunnitteluRoute: NakyvyysJaSuunnitteluRoute,
  PoytavaraupalveluRoute: PoytavaraupalveluRoute,
  VerkkosivutRoute: VerkkosivutRoute,
  YhteysRoute: YhteysRoute,
  YllapitoRoute: YllapitoRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTrackRoute: ApiTrackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiDashboardConversationsRoute: ApiDashboardConversationsRouteWithChildren,
  ApiDashboardFloorPlanRoute: ApiDashboardFloorPlanRoute,
  ApiDashboardLeadsRoute: ApiDashboardLeadsRouteWithChildren,
  ApiDashboardReservationsRoute: ApiDashboardReservationsRouteWithChildren,
  ApiDashboardSettingsRoute: ApiDashboardSettingsRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiDashboardVisitorsRoute: ApiDashboardVisitorsRoute,
  ApiRestaurantSettingsRoute: ApiRestaurantSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
